### ISSUE TITLE
How to convert the npy file of the coco skeleton with 18 key points into a bvh file

### ISSUE THREAD

**Issue by Kismetzc** [HW140701/VideoTo3dPoseAndBvh#21]
I want to use the coco_skeleton. But it seems that its class is incomplete compared to the other two in [bvh_skeleton](https://github.com/HW140701/VideoTo3dPoseAndBvh/blob/master/bvh_skeleton/coco_skeleton.py)

**Comment by Kismetzc** [comment]
你好，我现有有coco骨架（18个关键点）的npy数据。但是看到在bvh_skeleton里面，cmu_skeleton和human3.6_skeleton两种骨架是有代码写好直接可以转成bvh文件的，但是coco却没有。请问我应该怎么样仿写呢？

**Comment by sashapersonxyz** [comment]
@Kismetzc how did you manage to solve this problem?
