### ISSUE TITLE
关于一个output的报错

### ISSUE THREAD

**Issue by Lyceik** [HW140701/VideoTo3dPoseAndBvh#35]
作者您好，我尝试跑了一下您的代码，然后发现了如下报错，好像我这他没有生成处理后的文件，我想问问哪出问题了。。
![image](https://user-images.githubusercontent.com/54783810/158134054-a270bd06-8770-453a-b675-2cfdde0af599.png)

**Comment by HW140701** [comment]
看错误提示是创建输出文件夹失败了，自己手动创建下输出路径并确保路径存在吧

**Comment by Lyceik** [comment]
好的我去研究下，十分感谢！
