### ISSUE TITLE
关于原理的一些问题

### ISSUE THREAD

**Issue by baojunshan** [HW140701/VideoTo3dPoseAndBvh#38]
看了转换的代码，还是有一些问题，pose3d 是否能真正的转换成bvh？我感觉靠3d坐标，只能得到旋转角度，但比如手臂的自旋是如何计算的呢？比如一个T-pose，变成掌心向上，手臂的自旋角度计算是如何进行的，如果和3d模型绑定，会不会很奇怪啊？

**Comment by HW140701** [comment]
自旋的求解确实是一个问题。不能作为工业级别的动作绑定的源数据。目前没有跟这块的研究，应该有新的端到端的框架或者模型。

**Comment by baojunshan** [comment]
感谢回复，确实这块比较棘手
