### ISSUE TITLE
TypeError: Argument 'alpha' can not be treated as a double

### ISSUE THREAD

**Issue by MikeXuQ** [HW140701/VideoTo3dPoseAndBvh#5]
Do you what's wrong with this? It seems strange....

**Comment by HW140701** [comment]
May I ask which line of the file the error code is in？

**Comment by MikeXuQ** [comment]
Thanks for your reply! I have solved it. I just delete the code which triggers the problem.

**Comment by HW140701** [comment]
> Thanks for your reply! I have solved it. I just delete the code which triggers the problem.

Happy coding!
