### ISSUE TITLE
Error Alpha

### ISSUE THREAD

**Issue by Snouf-ID** [HW140701/VideoTo3dPoseAndBvh#9]
Hello !
I did a clean install twice but I still have this concern.

![image](https://user-images.githubusercontent.com/47319640/100885083-88ddea80-34b2-11eb-99fe-33503b4b3293.png)

**Comment by Snouf-ID** [comment]
I use https://www.gitmemory.com/issue/zh-plus/video-to-pose3D/35/664872529 and cast in float transparency for the cv2 call, and it's fine now.

**Comment by HW140701** [comment]
Thanks for your reply，I will update the code!
